VERIFY_DEVICE = 0
UPDATE_CONTROLLER = 1
GET_CONTROLLER_VERSION = 2
SET_TRANSFER_MODE = 3
GET_WIFI_NETWORKS = 4
CONNECT_TO_WIFI = 5
DISCONNECT_FROM_WIFI = 6
UNKNOWN_COMMAND = 255

#Verification codes
DEVICE_VERIFICATION_SUCCES = 0
DEVICE_VERIFICATION_MISSING = 1
DEVICE_VERIFICATION_INCORRECT_PASSKEY = 2

#WiFi connect results
WIFI_CONNECT_FAILED_UNKNOWN = 3
WIFI_CONNECT_SUCCES = 2
WIFI_CONNECT_FAILED_INC_PW = 1
WIFI_CONNECT_FAILED_INC_SSID = 0

#WiFi disconnect results
WIFI_DISCONNECT_FAILED = 0
WIFI_DISCONNECT_SUCCES = 1

#file transfer
FILE_TRANSFER_ENABLED = 1
FILE_TRANSFER_COMPLETE = 2
FILE_TRANSFER_PROGRESS = 3

#Update controller
CONTROLLER_INTERNET_ACCESS_TRUE = 0
CONTROLLER_INTERNET_ACCESS_FALSE = 1