VERIFY_DEVICE = 0
UPDATE_CONTROLLER = 1
GET_CONTROLLER_VERSION = 2
FILE_TRANSFER = 3
CONTROLLER_SETTINGS = 4
WIRELESS_SETTINGS = 5
AP_SETTINGS = 6
ETHERNET_SETTINGS = 7
CONTROLLER_PROGRAMS = 8
WWAN_SETTINGS = 9
REBOOT_CONTROLLER = 254
UNKNOWN_COMMAND = 255

#Verify device
DEVICE_VERIFICATION_SUCCESS = 0
DEVICE_VERIFICATION_MISSING = 1
DEVICE_VERIFICATION_INCORRECT_PASSKEY = 2

#Update controller
CHECK_FOR_UPDATE = 0
CONTROLLER_INTERNET_ACCESS_FALSE = 1
CONTROLLER_INTERNET_ACCESS_TRUE = 2
UPDATE_CONTROLLER_LOCAL = 3
UPDATE_LOCAL_SUCCESS = 4
UPDATE_FILE_CORRUPTED = 5
UPDATE_FILE_APROVED = 6

#check for update
CONTROLLER_UPDATE_AVAILABLE = 0
#

#transfer file
FILE_TRANSFER_ENABLED = 0
FILE_TRANSFER_COMPLETE = 1
FILE_TRANSFER_PROGRESS = 2


#ethernet settings
INIT_ETHERNET_SETTINGS = 0
SET_ETHERNET_SETTINGS = 1
SWITCH_ETHERNET_MODE = 2
#

#wireless settings
INIT_WIRELESS_SETTINGS = 0
GET_WIFI_NETWORKS = 1
GET_CONNECTED_DEVICES = 2
CONNECT_TO_WIFI = 3
DISCONNECT_FROM_WIFI = 4
SWITCH_WIRELESS_MODE = 5

#WiFi connect results
WIFI_CONNECT_FAILED_INC_SSID = 0
WIFI_CONNECT_FAILED_INC_PW = 1
WIFI_CONNECT_SUCCESS = 2
WIFI_CONNECT_FAILED_UNKNOWN = 3

#WiFi disconnect results
WIFI_DISCONNECT_FAILED = 0
WIFI_DISCONNECT_SUCCESS = 1
#

#access point settings
SET_AP_SETTINGS = 0
INIT_AP_SETTINGS = 1
#

#controller settings
INIT_CONTROLLER_SETTINGS = 0
SET_CONTROLLER_SETTINGS = 1
#

#controller programs
INIT_CONTROLLER_PROGRAMS = 0
SET_CONTROLLER_PROGRAMS = 1
#

#wwan settings
INIT_WWAN_SETTINGS = 0
SWITCH_WWAN = 1
SET_WWAN_SETTINGS = 2